### ISSUE TITLE
Implement canceling power off in the poweroff_callback function

### ISSUE THREAD

**Issue by frank1119** [FrankBoesing/T4_PowerButton#2]
Thanks for your handy library for powering off and resetting a Teensy and the possibilty of handling the power on/off pin.

I only have this request: Sometimes it comes in handy to be able to cancel the power off, so maybe it is possible to let the callback function return a value to indicate the power off should continue or not, e.g.:

```
static int (*__user_power_button_callback)(void);

FLASHMEM
void __int_power_button(void) {
  if (SNVS_HPSR & 0x40) {
    SNVS_HPCOMR |= (1 << 31)/* | (1 << 4)*/;
    SNVS_LPSR |= (1 << 18) | (1 << 17);
    int _discontinue = 0;
    if (__user_power_button_callback != nullptr)
        _discontinue = __user_power_button_callback();
    if( _discontinue == 0)
    {
        __disable_irq();
        NVIC_CLEAR_PENDING(IRQ_SNVS_ONOFF);
        arm_power_down();
    }
  }
}

FLASHMEM
void set_arm_power_button_callback(int (*fun_ptr)(void)) {
<rest of your code>
```

The usage could be:

```
int pwr_off_callback() {
    if( <some condition to cancel>)
        return 1;
    else
        return 0;
}
void setup() {
    set_arm_power_button_callback(&pwr_off_callback);
}

void loop {
}
```

Of course the header file has to be changed accordingly.

**Comment by FrankBoesing** [comment]
If you have tested this - can you creatd a PR (It shouldn't break old software using this library)
Thank you!

**Comment by frank1119** [comment]
I'll try. Never did that before, that is, creating a pull request. Thank you

**Comment by frank1119** [comment]
I think I created a pull request. I don't know whether I did this the right way or not. Feel free to do with it what you want.

**Comment by FrankBoesing** [comment]
Merged.
Thank you :)
