### ISSUE TITLE
No Serial output with MTP build

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/T4_PowerButton#4]
Added to MTP example : [https://forum.pjrc.com/threads/43050-MTP-Responder-Contribution?p=269448&viewfull=1#post269448](url)

Forcing a div/Zero error failed to show because the MTP usb stack is slow to start and connect to the PC .

As noted in that link - this change to '10' seconds allowed it to work:
`bool show_callstack(void)
{

  arm_dcache_delete((void*)&sRegInfo, sizeof(RegInfo));
  bool found = sRegInfo.marker == _marker;
  if (!found) return false;

#if (HARDFAULTSOUT==Serial)
  **while(!Serial && millis() < 10000){} // was :: 3000){}**
#endif
...`

I didn't try less - just went to 10 seconds and it worked as the MTP is slow.  As noted in the link - there has been a fault - so not waiting long enough to get Serial online prevents displaying the needed fault message.

**Comment by FrankBoesing** [comment]
Thank you!
https://github.com/FrankBoesing/T4_PowerButton/commit/41dde95858db8767b46eb2c9a95b846ad8078bf2#diff-0d2c19d5828a25e89fe6aa4dbe3879c4b46e5d767d2ddc82a81d54d09569ac8c

**Comment by Defragster** [comment]
! :)

@kurte @mjs513
